use_wandb: false
project_name: DPC
config_name: default

# kinetics, ucf, hmdb
dataset: kinetics
data_path: /home/seito/ssd2/kinetics/
#data_path: /groups1/gaa50131/datasets/kinetics
video_path: videos_700_hdf5
ann_path: kinetics-700-hdf5.json
only_best_checkpoint: false
clip_len: 5
n_clip: 8
# DPC, CPC, FGCPC
model: DPC
num_heads: 8
downsample: 3
pred_step: 3
input_size: 512
hidden_size: 512
kernel_size: 1
num_layers: 1
resize: 112
batch_size: 32
max_epoch: 20
num_workers: 2
outpath: out
gpu_ids: [0]
dropout: 0.1
lr: 0.001
weight_decay: 0.00001
grad_clip: 0.
dampening_rate: 0.1
patience: 5

seed: -1

mse_weight: 0.0
